[package]
name = "llm"
version = "4.0.0"
description = "Library for the LLM canister"
repository = "https://github.com/dfinity/llm/motoko"
keywords = [ "llm", "ai", "agent" ]
license = "MIT"

[dependencies]
core = "2.6.1"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "1.14.1"
